program WK;

uses
  Vcl.Forms,
  uHandle.Exception in 'Config\uHandle.Exception.pas',
  uMainView in 'uMainView.pas' {MainView},
  uSession.DTM in 'Config\uSession.DTM.pas' {SessionDTM: TDataModule},
  uConnection.FireDAC in 'Config\Connection\Drivers\FireDAC\uConnection.FireDAC.pas',
  uConnection.Interfaces in 'Config\Connection\uConnection.Interfaces.pas',
  uConnection.Factory in 'Config\Connection\uConnection.Factory.pas',
  uQry.Factory in 'Config\Connection\uQry.Factory.pas',
  uQry.Interfaces in 'Config\Connection\uQry.Interfaces.pas',
  uQry.FireDAC in 'Config\Connection\Drivers\FireDAC\uQry.FireDAC.pas',
  uConnection.Types in 'Config\Connection\uConnection.Types.pas',
  uEnv in 'Config\uEnv.pas',
  uMigration.Manager in 'Config\Migration\uMigration.Manager.pas',
  uMigration.Interfaces in 'Config\Migration\uMigration.Interfaces.pas',
  u01CreateCustomerTable.Migration in 'Config\Migration\u01CreateCustomerTable.Migration.pas',
  uMigration.Base in 'Config\Migration\uMigration.Base.pas',
  uMigration.Info in 'Config\Migration\uMigration.Info.pas',
  uCustomer.SQLBuilder.MySQL in 'Modules\Customer\SQLBuilder\uCustomer.SQLBuilder.MySQL.pas',
  uCustomer.SQLBuilder.Interfaces in 'Modules\Customer\SQLBuilder\uCustomer.SQLBuilder.Interfaces.pas',
  uMigration.Helper in 'Config\Migration\uMigration.Helper.pas',
  uCustomer.Controller.Interfaces in 'Modules\Customer\Controller\uCustomer.Controller.Interfaces.pas',
  uCustomer.Entity in 'Modules\Customer\Domain\Entity\uCustomer.Entity.pas',
  uEither in 'Config\uEither.pas',
  uCustomer.Controller in 'Modules\Customer\Controller\uCustomer.Controller.pas',
  uCustomer.Service.Interfaces in 'Modules\Customer\Domain\Service\uCustomer.Service.Interfaces.pas',
  uCustomer.Service in 'Modules\Customer\Domain\Service\uCustomer.Service.pas',
  uCustomer.Repository.Interfaces in 'Modules\Customer\Repository\uCustomer.Repository.Interfaces.pas',
  uCustomer.Repository.Factory in 'Modules\Customer\Repository\uCustomer.Repository.Factory.pas',
  uCustomer.Repository.SQL in 'Modules\Customer\Repository\uCustomer.Repository.SQL.pas',
  uCustomer.Validator.Interfaces in 'Modules\Customer\Domain\Validator\uCustomer.Validator.Interfaces.pas',
  uCustomer.Validator in 'Modules\Customer\Domain\Validator\uCustomer.Validator.pas',
  uCustomer.Entity.Interfaces in 'Modules\Customer\Domain\Entity\uCustomer.Entity.Interfaces.pas',
  uPageFilter in 'Config\uPageFilter.pas',
  uIndexResult in 'Config\uIndexResult.pas',
  uHlp in 'Config\uHlp.pas',
  uSelectWithFilter in 'Config\uSelectWithFilter.pas',
  uMemTable.Interfaces in 'Config\Connection\uMemTable.Interfaces.pas',
  uMemTable.FireDAC in 'Config\Connection\Drivers\FireDAC\uMemTable.FireDAC.pas',
  uMemTable.Factory in 'Config\Connection\uMemTable.Factory.pas',
  uCustomer.Mapper in 'Modules\Customer\Domain\Mapper\uCustomer.Mapper.pas',
  uScript.Interfaces in 'Config\Connection\uScript.Interfaces.pas',
  uScript.FireDAC in 'Config\Connection\Drivers\FireDAC\uScript.FireDAC.pas',
  uScript.Factory in 'Config\Connection\uScript.Factory.pas',
  uCustomer.ViewModel.Interfaces in 'Modules\Customer\ViewModel\uCustomer.ViewModel.Interfaces.pas',
  uCustomer.ViewModel in 'Modules\Customer\ViewModel\uCustomer.ViewModel.pas',
  uBase.Index.View in 'Shared\View\uBase.Index.View.pas' {BaseIndexView},
  uCustomer.Index.View in 'Modules\Customer\View\uCustomer.Index.View.pas' {CustomerIndexView},
  uBase.CreateUpdate.View in 'Shared\View\uBase.CreateUpdate.View.pas' {BaseCreateUpdateView},
  uCustomer.CreateUpdate.View in 'Modules\Customer\View\uCustomer.CreateUpdate.View.pas' {CustomerCreateUpdateView},
  uAlert.View in 'Shared\Helpers\uAlert.View.pas' {AlertView},
  uNotificationView in 'Shared\Helpers\uNotificationView.pas' {NotificationView},
  uYesOrNo.View in 'Shared\Helpers\uYesOrNo.View.pas' {YesOrNoView},
  uProduct.Index.View in 'Modules\Product\View\uProduct.Index.View.pas' {ProductIndexView},
  uProduct.SQLBuilder.MySQL in 'Modules\Product\SQLBuilder\uProduct.SQLBuilder.MySQL.pas',
  uProduct.ViewModel in 'Modules\Product\ViewModel\uProduct.ViewModel.pas',
  uProduct.ViewModel.Interfaces in 'Modules\Product\ViewModel\uProduct.ViewModel.Interfaces.pas',
  uProduct.CreateUpdate.View in 'Modules\Product\View\uProduct.CreateUpdate.View.pas' {ProductCreateUpdateView},
  uProduct.SQLBuilder.Interfaces in 'Modules\Product\SQLBuilder\uProduct.SQLBuilder.Interfaces.pas',
  uProduct.Repository.SQL in 'Modules\Product\Repository\uProduct.Repository.SQL.pas',
  uProduct.Repository.Interfaces in 'Modules\Product\Repository\uProduct.Repository.Interfaces.pas',
  uProduct.Repository.Factory in 'Modules\Product\Repository\uProduct.Repository.Factory.pas',
  uProduct.Validator in 'Modules\Product\Domain\Validator\uProduct.Validator.pas',
  uProduct.Validator.Interfaces in 'Modules\Product\Domain\Validator\uProduct.Validator.Interfaces.pas',
  uProduct.Service in 'Modules\Product\Domain\Service\uProduct.Service.pas',
  uProduct.Service.Interfaces in 'Modules\Product\Domain\Service\uProduct.Service.Interfaces.pas',
  uProduct.Mapper in 'Modules\Product\Domain\Mapper\uProduct.Mapper.pas',
  uProduct.Entity in 'Modules\Product\Domain\Entity\uProduct.Entity.pas',
  uProduct.Entity.Interfaces in 'Modules\Product\Domain\Entity\uProduct.Entity.Interfaces.pas',
  uProduct.Controller in 'Modules\Product\Controller\uProduct.Controller.pas',
  uProduct.Controller.Interfaces in 'Modules\Product\Controller\uProduct.Controller.Interfaces.pas',
  u02CreateProductTable.Migration in 'Config\Migration\u02CreateProductTable.Migration.pas',
  uSalesOrder.SQLBuilder.MySQL in 'Modules\SalesOrder\SQLBuilder\uSalesOrder.SQLBuilder.MySQL.pas',
  uSalesOrder.ViewModel in 'Modules\SalesOrder\ViewModel\uSalesOrder.ViewModel.pas',
  uSalesOrder.ViewModel.Interfaces in 'Modules\SalesOrder\ViewModel\uSalesOrder.ViewModel.Interfaces.pas',
  uSalesOrder.SQLBuilder.Interfaces in 'Modules\SalesOrder\SQLBuilder\uSalesOrder.SQLBuilder.Interfaces.pas',
  uSalesOrder.Repository.SQL in 'Modules\SalesOrder\Repository\uSalesOrder.Repository.SQL.pas',
  uSalesOrder.Repository.Interfaces in 'Modules\SalesOrder\Repository\uSalesOrder.Repository.Interfaces.pas',
  uSalesOrder.Repository.Factory in 'Modules\SalesOrder\Repository\uSalesOrder.Repository.Factory.pas',
  uSalesOrder.Validator in 'Modules\SalesOrder\Domain\Validator\uSalesOrder.Validator.pas',
  uSalesOrder.Validator.Interfaces in 'Modules\SalesOrder\Domain\Validator\uSalesOrder.Validator.Interfaces.pas',
  uSalesOrder.Service in 'Modules\SalesOrder\Domain\Service\uSalesOrder.Service.pas',
  uSalesOrder.Service.Interfaces in 'Modules\SalesOrder\Domain\Service\uSalesOrder.Service.Interfaces.pas',
  uSalesOrder.Mapper in 'Modules\SalesOrder\Domain\Mapper\uSalesOrder.Mapper.pas',
  uSalesOrder.Entity in 'Modules\SalesOrder\Domain\Entity\uSalesOrder.Entity.pas',
  uSalesOrder.Entity.Interfaces in 'Modules\SalesOrder\Domain\Entity\uSalesOrder.Entity.Interfaces.pas',
  uSalesOrder.Controller in 'Modules\SalesOrder\Controller\uSalesOrder.Controller.pas',
  uSalesOrder.Controller.Interfaces in 'Modules\SalesOrder\Controller\uSalesOrder.Controller.Interfaces.pas',
  u03CreateSalesOrderTable.Migration in 'Config\Migration\u03CreateSalesOrderTable.Migration.pas',
  uSalesOrder.CreateUpdate.View in 'Modules\SalesOrder\View\uSalesOrder.CreateUpdate.View.pas' {SalesOrderCreateUpdateView},
  uSalesOrder.Index.View in 'Modules\SalesOrder\View\uSalesOrder.Index.View.pas' {SalesOrderIndexView},
  u04CreateSalesOrderProductTable.Migration in 'Config\Migration\u04CreateSalesOrderProductTable.Migration.pas',
  uSalesOrderProduct.SQLBuilder.Interfaces in 'Modules\SalesOrder\SQLBuilder\uSalesOrderProduct.SQLBuilder.Interfaces.pas',
  uSalesOrderProduct.SQLBuilder.MySQL in 'Modules\SalesOrder\SQLBuilder\uSalesOrderProduct.SQLBuilder.MySQL.pas',
  uSalesOrderProduct.Entity.Interfaces in 'Modules\SalesOrder\Domain\Entity\uSalesOrderProduct.Entity.Interfaces.pas',
  uSalesOrderProduct.Entity in 'Modules\SalesOrder\Domain\Entity\uSalesOrderProduct.Entity.pas',
  uThreadCustom in 'Shared\Helpers\uThreadCustom.pas',
  uWithoutViewModel.View in 'Shared\View\uWithoutViewModel.View.pas' {WithoutViewModelView};

{$R *.res}

begin
  ReportMemoryLeaksOnShutdown := DebugHook <> 0;
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TSessionDTM, SessionDTM);
  Application.CreateForm(TMainView, MainView);
  Application.CreateForm(TNotificationView, NotificationView);
  Application.Run;
end.
